#### 1. Write a Python Program to Add Two Matrices?

In [34]:
# using numpy
import numpy as np
#first matrix
r=int(input("enter the number of rows for first matrix: "))
c=int(input("enter the number of columns for first matrix: "))
print("Enter the matrix elements for first matrix")
mat1 = [[int(input()) for i in range(c)] for i in range(r)]
#second matrix
r=int(input("enter the number of rows for second matrix: "))
c=int(input("enter the number of columns for second matrix: "))
print("Enter the matrix elements for second matrix")
mat2 = [[int(input()) for i in range(c)] for i in range(r)]

A=np.array(mat1)
B=np.array(mat2)
C=A+B #using numpy addition

print("Addition of matrix")
print(C.view(),end="")

enter the number of rows for first matrix: 3
enter the number of columns for first matrix: 3
Enter the matrix elements for first matrix
1
2
3
4
5
6
7
8
9
enter the number of rows for second matrix: 3
enter the number of columns for second matrix: 3
Enter the matrix elements for second matrix
1
2
3
4
5
6
7
8
9
Addition of matrix
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

#### 2. Write a Python Program to Multiply Two Matrices?

In [37]:
# using numpy
import numpy as np
#first matrix
r=int(input("enter the number of rows for first matrix: "))
c=int(input("enter the number of columns for first matrix: "))
print("Enter the matrix elements for first matrix")
mat1 = [[int(input()) for i in range(c)] for i in range(r)]
#second matrix
r=int(input("enter the number of rows for second matrix: "))
c=int(input("enter the number of columns for second matrix: "))
print("Enter the matrix elements for second matrix")
mat2 = [[int(input()) for i in range(c)] for i in range(r)]

A=np.array(mat1)
B=np.array(mat2)
C=A.dot(B)#using numpy array dot method

print("Multiplication of matrix")
print(C.view(),end="")

enter the number of rows for first matrix: 3
enter the number of columns for first matrix: 3
Enter the matrix elements for first matrix
1
2
3
4
5
6
7
8
9
enter the number of rows for second matrix: 3
enter the number of columns for second matrix: 3
Enter the matrix elements for second matrix
1
2
3
4
5
6
7
8
9
Multiplication of matrix
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

#### 3. Write a Python Program to Transpose a Matrix?


In [38]:
# using numpy
import numpy as np
#matrix input
r=int(input("enter the number of rows for first matrix: "))
c=int(input("enter the number of columns for first matrix: "))
print("Enter the matrix elements for first matrix")
mat1 = [[int(input()) for i in range(c)] for i in range(r)]

A=np.array(mat1)

C=A.transpose()

print("Transpose of matrix")
print(C.view(),end="")

enter the number of rows for first matrix: 3
enter the number of columns for first matrix: 3
Enter the matrix elements for first matrix
1
2
3
4
5
6
7
8
9
Transpose of matrix
[[1 4 7]
 [2 5 8]
 [3 6 9]]

#### 4. Write a Python Program to Sort Words in Alphabetic Order?

In [56]:
string=input()
print(f" Before Sorting: {string}")
words=string.split(" ")
words.sort() #using sort method
string=" ".join(words)
print(f" After Sorting: {string}")

hello! i am abhishek kaddipudi
 Before Sorting: hello! i am abhishek kaddipudi
 After Sorting: abhishek am hello! i kaddipudi


#### 5. Write a Python Program to Remove Punctuation From a String?

In [67]:
punc = """!()-[]{};:'"\,<>./?@#$%^&*_~"""#all the punctuations available

text=input("Enter the text to remove punctuation:\n")
for i in punc:
    text=text.replace(i,"")
print(f"\nAfter removing:\n{text}")

Enter the text to remove punctuation:
punctuation marks are a symbol to create and support meaning within a sentence or to break it up. Examples of different punctuation marks include: full stops (.), commas (,), question marks (?), exclamation marks (!), colons (:), semi-colons (;), apostrophes (') and speech marks (",").

After removing:
punctuation marks are a symbol to create and support meaning within a sentence or to break it up Examples of different punctuation marks include full stops  commas  question marks  exclamation marks  colons  semicolons  apostrophes  and speech marks 
